# set for TableBank: https://github.com/doc-analysis/TableBank
_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  MASK_ON: False
  WEIGHTS: "./output/PubLayNet_table/FasterRCNN/051601/model_final.pth"
  PIXEL_STD: [57.375, 57.120, 58.395]
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 64
    WIDTH_PER_GROUP: 4
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 1
  RETINANET:
    NUM_CLASSES: 1
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
  RPN:
    BATCH_SIZE_PER_IMAGE: 512
DATASETS:
  TRAIN: ("tablebank_train",)
  TEST: ("tablebank_val",)
SOLVER:
  STEPS: (5600, 8000, )
  MAX_ITER: 9600
  BASE_LR: 0.01
  GAMMA: 0.1
  WARMUP_FACTOR: 0.3333333333333333
  WARMUP_ITERS: 2
  CHECKPOINT_PERIOD: 5000
  IMS_PER_BATCH: 8
INPUT:
  MIN_SIZE_TRAIN: (400,)
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 400
  MAX_SIZE_TEST: 512
TEST:
  AUG:
    FLIP: False
OUTPUT_DIR: "./output/ICDAR2019/FasterRCNN"