_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  MASK_ON: True
  WEIGHTS: "/home/mojianqiao/work/detectron2/output/PubLayNet_table/MaskRCNN_R101FPN/051801/model_final.pth"
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 1
  RETINANET:
    NUM_CLASSES: 1
#  RPN:
#    BATCH_SIZE_PER_IMAGE: 512
#  ROI_MASK_HEAD:
#    NUM_CONV: 4
#    POOLER_RESOLUTION: 28
#    POOLER_SAMPLING_RATIO: 2
DATASETS:
  TRAIN: ("ICDAR2019_train",)
  TEST: ("ICDAR2019_val",)
SOLVER:
  STEPS: (6400,  10000)
  MAX_ITER: 11000
  BASE_LR: 0.01
  GAMMA: 0.1
  WARMUP_FACTOR: 0.3333333333333333
  WARMUP_ITERS: 20
  CHECKPOINT_PERIOD: 6400
  IMS_PER_BATCH: 8
INPUT:
  MIN_SIZE_TRAIN: (400,)
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 400
  MAX_SIZE_TEST: 512
OUTPUT_DIR: "./output/PubLayNet_table/MaskRCNN"
