# set for PubLayNet: https://github.com/ibm-aur-nlp/PubLayNet
_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  MASK_ON: True
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 1
  RETINANET:
    NUM_CLASSES: 1
#  RPN:
#    BATCH_SIZE_PER_IMAGE: 512
#  ROI_MASK_HEAD:
#    NUM_CONV: 4
#    POOLER_RESOLUTION: 28
#    POOLER_SAMPLING_RATIO: 2
DATASETS:
  TRAIN: ("table_train",)
  TEST: ("table_val",)
SOLVER:
  STEPS: (10000, 11500) # MUST minus start iteration
  MAX_ITER: 12500
  BASE_LR: 0.01
  GAMMA: 0.1
  WARMUP_FACTOR: 0.3333333333333333
  WARMUP_ITERS: 30
  CHECKPOINT_PERIOD: 10000
  IMS_PER_BATCH: 8
INPUT:
  MIN_SIZE_TRAIN: (400,)
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 400
  MAX_SIZE_TEST: 512
OUTPUT_DIR: "./output/PubLayNet_table/MaskRCNN"
